name: opencv_ffi
description: An FFI implementation of the C++ OpenCV library in Dart, with video I/O, image encodings and processing, and some GUI elements.
version: 1.2.0
repository: https://github.com/Levi-Lesches/opencv_ffi
homepage: https://opencv.org

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  ffi: ^2.0.2

dev_dependencies:
  ffigen: ^11.0.0
  test: ^1.21.0
  very_good_analysis: ^5.0.0+1

topics: 
  - ffi
  - opencv
  - video
  - image
  - camera

ffigen:
  # Run with `dart run ffigen --config ffigen.yaml -v severe`.
  name: OpenCVBindings
  description: |
    Bindings for `src/opencv_ffi.h`.

    Regenerate bindings with `dart run ffigen --config ffigen.yaml -v severe`.
  output: "lib/src/generated/opencv_ffi_bindings.dart"
  headers:
    entry-points:
      - 'src/opencv_ffi.h'
    include-directives:
      - 'src/opencv_ffi.h'
  comments:
    style: any
    length: full

  type-map:
    native-types:
      'char':  # Converts `char` to `Utf8` instead of `Char`
        'lib': 'pkg_ffi'
        'c-type': 'Utf8'
        'dart-type': 'Utf8'
