name: burt_network
description: A starting point for Dart libraries or applications.
version: 1.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.2

# Add regular dependencies here.
dependencies:
  libserialport: ^0.3.0+1
  logger: ^2.0.2
  meta: ^1.9.1
  protobuf: ^3.0.0

dev_dependencies:
  test: ^1.21.0
  very_good_analysis: ^5.0.0+1
