name: subsystems
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: 3.2.2

# Add regular dependencies here.
dependencies:
  burt_network: 
    git: https://github.com/BinghamtonRover/Networking.git
  collection: ^1.18.0
  csv: ^6.0.0
  ffi: 2.1.0
  libserialport: ^0.3.0+1
  meta: ^1.14.0
  osc: ^1.0.0
  protobuf: ^3.1.0

dev_dependencies:
  ffigen: ^11.0.0
  test: ^1.21.0
  very_good_analysis: ^5.0.0+1
